name: workflow
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      # Étape 1 : Cloner le dépôt
      - uses: actions/checkout@v3
      # Installer Python
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name : vérifier la evrsion du Python
        run: python --version