name: workflow
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      # Étape 1 : Cloner le dépôt
      - uses: actions/checkout@v3
      # Etape 2 : Installer Python
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      # Etape 3 : Installer les dépendences du Python
      - name : Installer les dépendences
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      # Étape 4 : Préparer l'environnement et télécharger les données avec DVC
      - name: Prepare Environment
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
            # Exécuter dvc pull pour télécharger les artefacts
            dvc pull

            # Lister les fichiers pour vérifier que les artefacts ont été téléchargés
            ls -l