name: workflow
on: [push]
permissions: 
  contents : read
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      # Étape 1 : Cloner le dépôt
      - uses: actions/checkout@v3
      # Étape 2 : Lister les fichiers clonés
      - name: List files in repository
        run: |
          echo "Files in the repository:"
          ls -la
    